# Monitored sampling interval in seconds
monitor.interval.seconds=20

# Relative path to the process watch list
monitor.process.watchlist=processes.txt
# Relative path to the network interface exclude list
monitor.network.interface.exclude=network-interface-excludes.txt

# REST API configuration
rest.port=8080

# MQTT publisher configuration
mqtt.broker.uri=ssl://mibroker:8883
mqtt.topic.template=charodaemon/host/{clientId}/metrics
mqtt.sample.window=5
mqtt.client.id=charod
mqtt.username=usuario
mqtt.password=contrasesesenia

# Agent availability (LWT)
mqtt.availability.enabled=true
mqtt.availability.topic=charodaemon/host/{clientId}/status
mqtt.retain.availability=true
